USE [master]
GO
/****** Object:  Database [QuanLyGiaoVienVaHocSinh]    Script Date: 07/05/2017 3:33:57 CH ******/
CREATE DATABASE [QuanLyGiaoVienVaHocSinh]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyGiaoVienVaHocSinh', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\QuanLyGiaoVienVaHocSinh.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLyGiaoVienVaHocSinh_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\QuanLyGiaoVienVaHocSinh_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET COMPATIBILITY_LEVEL = 130
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyGiaoVienVaHocSinh].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET ARITHABORT OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET  DISABLE_BROKER 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET  MULTI_USER 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET DB_CHAINING OFF 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET QUERY_STORE = OFF
GO
USE [QuanLyGiaoVienVaHocSinh]
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO
USE [QuanLyGiaoVienVaHocSinh]
GO
/****** Object:  Table [dbo].[Ban]    Script Date: 07/05/2017 3:33:58 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ban](
	[MaBan] [varchar](10) NOT NULL,
	[TenBan] [nvarchar](50) NULL,
	[NoiDung] [nvarchar](100) NULL,
 CONSTRAINT [PK_Ban] PRIMARY KEY CLUSTERED 
(
	[MaBan] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[BanPhuTrachMonHoc]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BanPhuTrachMonHoc](
	[MaBan] [varchar](10) NOT NULL,
	[MaMonHoc] [varchar](10) NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[GiaoVien]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GiaoVien](
	[CMT] [int] IDENTITY(1,1) NOT NULL,
	[TenGV] [nvarchar](50) NOT NULL,
	[NgaySinh] [date] NULL,
	[GioiTinh] [bit] NULL,
	[SDT] [varchar](11) NULL,
	[Email] [nchar](30) NULL,
	[DiaChi] [nvarchar](100) NULL,
	[QueQuan] [nvarchar](100) NULL,
	[DanToc] [nvarchar](20) NULL,
	[TonGiao] [nvarchar](20) NULL,
 CONSTRAINT [PK_GiaoVien] PRIMARY KEY CLUSTERED 
(
	[CMT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[GiaoVienDayLopMH]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GiaoVienDayLopMH](
	[MaGiaoVien] [int] NOT NULL,
	[MaLopMH] [varchar](10) NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[GiaoVienThuocBan]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[GiaoVienThuocBan](
	[MaGiaoVien] [int] NOT NULL,
	[MaBan] [varchar](10) NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[HocSinh]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[HocSinh](
	[MaHS] [int] IDENTITY(1,1) NOT NULL,
	[TenHS] [nvarchar](50) NOT NULL,
	[NgaySinh] [date] NULL,
	[GioiTinh] [bit] NULL,
	[DiaChi] [nvarchar](100) NULL,
	[QueQuan] [nvarchar](100) NULL,
	[DanToc] [nvarchar](20) NULL,
	[TonGiao] [nvarchar](20) NULL,
 CONSTRAINT [PK_HocSinh] PRIMARY KEY CLUSTERED 
(
	[MaHS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Khoi]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Khoi](
	[MaKhoi] [varchar](10) NOT NULL,
	[TenKhoi] [nvarchar](50) NULL,
 CONSTRAINT [PK_Khoi] PRIMARY KEY CLUSTERED 
(
	[MaKhoi] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Lop]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Lop](
	[MaLop] [varchar](10) NOT NULL,
	[TenLop] [nvarchar](50) NULL,
 CONSTRAINT [PK_Lop] PRIMARY KEY CLUSTERED 
(
	[MaLop] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LopHocLopMonHoc]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LopHocLopMonHoc](
	[MaLop] [varchar](10) NOT NULL,
	[MaLopMH] [varchar](10) NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[LopMonHoc]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LopMonHoc](
	[MaLopMH] [varchar](10) NOT NULL,
	[TenLopMH] [nvarchar](50) NULL,
 CONSTRAINT [PK_LopMonHoc] PRIMARY KEY CLUSTERED 
(
	[MaLopMH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[MonHoc]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[MonHoc](
	[MaMonHoc] [varchar](10) NOT NULL,
	[TenMonHoc] [nvarchar](50) NULL,
	[NDMonHoc] [nvarchar](50) NULL,
 CONSTRAINT [PK_MonHoc] PRIMARY KEY CLUSTERED 
(
	[MaMonHoc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[NguoiDung]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NguoiDung](
	[TenDN] [varchar](20) NOT NULL,
	[MatKhau] [varchar](20) NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PhanGiaoVienCN]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PhanGiaoVienCN](
	[MaGiaoVien] [int] NOT NULL,
	[MaLop] [varchar](10) NOT NULL,
	[ID] [int] NOT NULL,
 CONSTRAINT [PK_PhanGiaoVienCN] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PhanKhoi]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PhanKhoi](
	[MaLop] [varchar](10) NOT NULL,
	[MaKhoi] [varchar](10) NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PhanLMH]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PhanLMH](
	[MaMH] [varchar](10) NOT NULL,
	[MaLopMH] [varchar](10) NOT NULL
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[PhanLop]    Script Date: 07/05/2017 3:33:59 CH ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PhanLop](
	[MaHS] [int] NOT NULL,
	[MaLop] [varchar](10) NOT NULL
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[BanPhuTrachMonHoc]  WITH CHECK ADD  CONSTRAINT [FK_BanPhuTrachMonHoc_Ban1] FOREIGN KEY([MaBan])
REFERENCES [dbo].[Ban] ([MaBan])
GO
ALTER TABLE [dbo].[BanPhuTrachMonHoc] CHECK CONSTRAINT [FK_BanPhuTrachMonHoc_Ban1]
GO
ALTER TABLE [dbo].[BanPhuTrachMonHoc]  WITH CHECK ADD  CONSTRAINT [FK_BanPhuTrachMonHoc_MonHoc1] FOREIGN KEY([MaMonHoc])
REFERENCES [dbo].[MonHoc] ([MaMonHoc])
GO
ALTER TABLE [dbo].[BanPhuTrachMonHoc] CHECK CONSTRAINT [FK_BanPhuTrachMonHoc_MonHoc1]
GO
ALTER TABLE [dbo].[GiaoVienDayLopMH]  WITH CHECK ADD  CONSTRAINT [FK_GiaoVienDayLopMH_GiaoVien1] FOREIGN KEY([MaGiaoVien])
REFERENCES [dbo].[GiaoVien] ([CMT])
GO
ALTER TABLE [dbo].[GiaoVienDayLopMH] CHECK CONSTRAINT [FK_GiaoVienDayLopMH_GiaoVien1]
GO
ALTER TABLE [dbo].[GiaoVienDayLopMH]  WITH CHECK ADD  CONSTRAINT [FK_GiaoVienDayLopMH_LopMonHoc] FOREIGN KEY([MaLopMH])
REFERENCES [dbo].[LopMonHoc] ([MaLopMH])
GO
ALTER TABLE [dbo].[GiaoVienDayLopMH] CHECK CONSTRAINT [FK_GiaoVienDayLopMH_LopMonHoc]
GO
ALTER TABLE [dbo].[GiaoVienThuocBan]  WITH CHECK ADD  CONSTRAINT [FK_GiaoVienThuocBan_Ban1] FOREIGN KEY([MaBan])
REFERENCES [dbo].[Ban] ([MaBan])
GO
ALTER TABLE [dbo].[GiaoVienThuocBan] CHECK CONSTRAINT [FK_GiaoVienThuocBan_Ban1]
GO
ALTER TABLE [dbo].[GiaoVienThuocBan]  WITH CHECK ADD  CONSTRAINT [FK_GiaoVienThuocBan_GiaoVien1] FOREIGN KEY([MaGiaoVien])
REFERENCES [dbo].[GiaoVien] ([CMT])
GO
ALTER TABLE [dbo].[GiaoVienThuocBan] CHECK CONSTRAINT [FK_GiaoVienThuocBan_GiaoVien1]
GO
ALTER TABLE [dbo].[LopHocLopMonHoc]  WITH CHECK ADD  CONSTRAINT [FK_LopHocLopMonHoc_Lop1] FOREIGN KEY([MaLop])
REFERENCES [dbo].[Lop] ([MaLop])
GO
ALTER TABLE [dbo].[LopHocLopMonHoc] CHECK CONSTRAINT [FK_LopHocLopMonHoc_Lop1]
GO
ALTER TABLE [dbo].[LopHocLopMonHoc]  WITH CHECK ADD  CONSTRAINT [FK_LopHocLopMonHoc_LopMonHoc1] FOREIGN KEY([MaLopMH])
REFERENCES [dbo].[LopMonHoc] ([MaLopMH])
GO
ALTER TABLE [dbo].[LopHocLopMonHoc] CHECK CONSTRAINT [FK_LopHocLopMonHoc_LopMonHoc1]
GO
ALTER TABLE [dbo].[PhanGiaoVienCN]  WITH CHECK ADD  CONSTRAINT [FK_PhanGiaoVienCN_GiaoVien] FOREIGN KEY([MaGiaoVien])
REFERENCES [dbo].[GiaoVien] ([CMT])
GO
ALTER TABLE [dbo].[PhanGiaoVienCN] CHECK CONSTRAINT [FK_PhanGiaoVienCN_GiaoVien]
GO
ALTER TABLE [dbo].[PhanGiaoVienCN]  WITH CHECK ADD  CONSTRAINT [FK_PhanGiaoVienCN_Lop] FOREIGN KEY([MaLop])
REFERENCES [dbo].[Lop] ([MaLop])
GO
ALTER TABLE [dbo].[PhanGiaoVienCN] CHECK CONSTRAINT [FK_PhanGiaoVienCN_Lop]
GO
ALTER TABLE [dbo].[PhanKhoi]  WITH CHECK ADD  CONSTRAINT [FK_PhanKhoi_Khoi] FOREIGN KEY([MaKhoi])
REFERENCES [dbo].[Khoi] ([MaKhoi])
GO
ALTER TABLE [dbo].[PhanKhoi] CHECK CONSTRAINT [FK_PhanKhoi_Khoi]
GO
ALTER TABLE [dbo].[PhanKhoi]  WITH CHECK ADD  CONSTRAINT [FK_PhanKhoi_Lop] FOREIGN KEY([MaLop])
REFERENCES [dbo].[Lop] ([MaLop])
GO
ALTER TABLE [dbo].[PhanKhoi] CHECK CONSTRAINT [FK_PhanKhoi_Lop]
GO
ALTER TABLE [dbo].[PhanLMH]  WITH CHECK ADD  CONSTRAINT [FK_PhanLMH_LopMonHoc] FOREIGN KEY([MaLopMH])
REFERENCES [dbo].[LopMonHoc] ([MaLopMH])
GO
ALTER TABLE [dbo].[PhanLMH] CHECK CONSTRAINT [FK_PhanLMH_LopMonHoc]
GO
ALTER TABLE [dbo].[PhanLMH]  WITH CHECK ADD  CONSTRAINT [FK_PhanLMH_MonHoc] FOREIGN KEY([MaMH])
REFERENCES [dbo].[MonHoc] ([MaMonHoc])
GO
ALTER TABLE [dbo].[PhanLMH] CHECK CONSTRAINT [FK_PhanLMH_MonHoc]
GO
ALTER TABLE [dbo].[PhanLop]  WITH CHECK ADD  CONSTRAINT [FK_PhanLop_HocSinh] FOREIGN KEY([MaHS])
REFERENCES [dbo].[HocSinh] ([MaHS])
GO
ALTER TABLE [dbo].[PhanLop] CHECK CONSTRAINT [FK_PhanLop_HocSinh]
GO
ALTER TABLE [dbo].[PhanLop]  WITH CHECK ADD  CONSTRAINT [FK_PhanLop_Lop] FOREIGN KEY([MaLop])
REFERENCES [dbo].[Lop] ([MaLop])
GO
ALTER TABLE [dbo].[PhanLop] CHECK CONSTRAINT [FK_PhanLop_Lop]
GO
USE [master]
GO
ALTER DATABASE [QuanLyGiaoVienVaHocSinh] SET  READ_WRITE 
GO
